create table products (
	id INT,
	name TEXT,
	category VARCHAR(11),
	description TEXT,
	price DECIMAL(7,4)
);
insert into products (id, name, category, description, price) values (1, 'morbi', 'Toys', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 77.3629);
insert into products (id, name, category, description, price) values (2, 'metus sapien ut', 'Toys', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', 11.0407);
insert into products (id, name, category, description, price) values (3, 'in congue', 'Home', 'velit eu est congue elementum in hac habitasse platea dictumst morbi', 99.8107);
insert into products (id, name, category, description, price) values (4, 'dapibus', 'Fashion', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', 98.5349);
insert into products (id, name, category, description, price) values (5, 'phasellus', 'Fashion', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit', 88.6974);
insert into products (id, name, category, description, price) values (6, 'varius integer', 'Fashion', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', 97.2394);
insert into products (id, name, category, description, price) values (7, 'ac', 'Toys', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 9.0886);
insert into products (id, name, category, description, price) values (8, 'etiam', 'Fashion', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 14.7929);
insert into products (id, name, category, description, price) values (9, 'in', 'Electronics', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', 130.5758);
insert into products (id, name, category, description, price) values (10, 'massa id lobortis', 'Electronics', 'in sagittis dui vel nisl duis ac nibh fusce lacus', 101.6736);
insert into products (id, name, category, description, price) values (11, 'magna', 'Other', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 69.2074);
insert into products (id, name, category, description, price) values (12, 'nulla pede ullamcorper', 'Electronics', 'nulla sed accumsan felis ut at dolor quis odio consequat', 72.0003);
insert into products (id, name, category, description, price) values (13, 'congue vivamus metus', 'Home', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius', 102.6386);
insert into products (id, name, category, description, price) values (14, 'est', 'Toys', 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', 24.3417);
insert into products (id, name, category, description, price) values (15, 'congue', 'Fashion', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 127.3012);
insert into products (id, name, category, description, price) values (16, 'pede posuere', 'Home', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula', 128.3605);
insert into products (id, name, category, description, price) values (17, 'vestibulum ac', 'Home', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa', 149.4001);
insert into products (id, name, category, description, price) values (18, 'libero', 'Home', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 133.0751);
insert into products (id, name, category, description, price) values (19, 'lobortis', 'Home', 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', 15.1056);
insert into products (id, name, category, description, price) values (20, 'quisque erat eros', 'Home', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 51.4141);
insert into products (id, name, category, description, price) values (21, 'justo', 'Other', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo', 102.8181);
insert into products (id, name, category, description, price) values (22, 'vestibulum', 'Toys', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 138.1005);
insert into products (id, name, category, description, price) values (23, 'vestibulum', 'Electronics', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in', 147.0537);
insert into products (id, name, category, description, price) values (24, 'vel pede', 'Fashion', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', 122.4556);
insert into products (id, name, category, description, price) values (25, 'volutpat sapien arcu', 'Art', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi', 73.0223);
insert into products (id, name, category, description, price) values (26, 'sit amet sem', 'Art', 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 33.6086);
insert into products (id, name, category, description, price) values (27, 'sed justo pellentesque', 'Other', 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', 3.8083);
insert into products (id, name, category, description, price) values (28, 'semper interdum', 'Fashion', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 136.3548);
insert into products (id, name, category, description, price) values (29, 'nulla pede ullamcorper', 'Fashion', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', 127.5935);
insert into products (id, name, category, description, price) values (30, 'integer a nibh', 'Fashion', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 91.6562);
insert into products (id, name, category, description, price) values (31, 'proin eu', 'Fashion', 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 81.2516);
insert into products (id, name, category, description, price) values (32, 'ultrices aliquet maecenas', 'Toys', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 9.3261);
insert into products (id, name, category, description, price) values (33, 'felis fusce', 'Electronics', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 103.8081);
insert into products (id, name, category, description, price) values (34, 'hendrerit at vulputate', 'Other', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', 74.1172);
insert into products (id, name, category, description, price) values (35, 'neque libero convallis', 'Fashion', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam', 119.9994);
insert into products (id, name, category, description, price) values (36, 'integer aliquet massa', 'Art', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 45.3821);
insert into products (id, name, category, description, price) values (37, 'lorem', 'Toys', 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 124.3235);
insert into products (id, name, category, description, price) values (38, 'a pede', 'Toys', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 100.8653);
insert into products (id, name, category, description, price) values (39, 'sit amet diam', 'Toys', 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 57.8445);
insert into products (id, name, category, description, price) values (40, 'pharetra magna', 'Electronics', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id', 43.1372);
insert into products (id, name, category, description, price) values (41, 'erat eros', 'Other', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam', 42.9131);
insert into products (id, name, category, description, price) values (42, 'primis in', 'Electronics', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 80.3333);
insert into products (id, name, category, description, price) values (43, 'sit amet diam', 'Art', 'eget semper rutrum nulla nunc purus phasellus in felis donec', 97.3329);
insert into products (id, name, category, description, price) values (44, 'vestibulum', 'Toys', 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', 20.0509);
insert into products (id, name, category, description, price) values (45, 'quis odio', 'Electronics', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', 86.8113);
insert into products (id, name, category, description, price) values (46, 'duis bibendum', 'Home', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 143.5867);
insert into products (id, name, category, description, price) values (47, 'neque aenean auctor', 'Other', 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', 4.6891);
insert into products (id, name, category, description, price) values (48, 'nam ultrices', 'Art', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 81.2226);
insert into products (id, name, category, description, price) values (49, 'accumsan felis', 'Toys', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 93.0178);
insert into products (id, name, category, description, price) values (50, 'at turpis', 'Electronics', 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 101.1296);
insert into products (id, name, category, description, price) values (51, 'sit amet consectetuer', 'Toys', 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis', 106.6631);
insert into products (id, name, category, description, price) values (52, 'aliquam augue', 'Art', 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 30.6379);
insert into products (id, name, category, description, price) values (53, 'ipsum primis', 'Home', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', 33.0285);
insert into products (id, name, category, description, price) values (54, 'dolor sit amet', 'Home', 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', 107.517);
insert into products (id, name, category, description, price) values (55, 'sapien urna pretium', 'Other', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 50.3994);
insert into products (id, name, category, description, price) values (56, 'mi', 'Fashion', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', 101.3896);
insert into products (id, name, category, description, price) values (57, 'a suscipit nulla', 'Home', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue', 146.4756);
insert into products (id, name, category, description, price) values (58, 'dictumst maecenas ut', 'Electronics', 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum', 5.1096);
insert into products (id, name, category, description, price) values (59, 'blandit mi in', 'Home', 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 141.554);
insert into products (id, name, category, description, price) values (60, 'quis turpis', 'Art', 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', 2.764);
insert into products (id, name, category, description, price) values (61, 'amet nunc', 'Home', 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 145.314);
insert into products (id, name, category, description, price) values (62, 'phasellus id', 'Home', 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 73.1533);
insert into products (id, name, category, description, price) values (63, 'nunc purus phasellus', 'Home', 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 143.7422);
insert into products (id, name, category, description, price) values (64, 'et magnis dis', 'Electronics', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 99.7103);
insert into products (id, name, category, description, price) values (65, 'a', 'Other', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 58.0192);
insert into products (id, name, category, description, price) values (66, 'interdum eu tincidunt', 'Electronics', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', 47.4238);
insert into products (id, name, category, description, price) values (67, 'nulla eget', 'Art', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 80.9269);
insert into products (id, name, category, description, price) values (68, 'sapien', 'Fashion', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 61.4678);
insert into products (id, name, category, description, price) values (69, 'aliquet massa', 'Other', 'in felis donec semper sapien a libero nam dui proin leo', 32.8571);
insert into products (id, name, category, description, price) values (70, 'pede lobortis ligula', 'Electronics', 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 4.5345);
insert into products (id, name, category, description, price) values (71, 'ut', 'Fashion', 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', 40.2172);
insert into products (id, name, category, description, price) values (72, 'amet', 'Electronics', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante', 48.1243);
insert into products (id, name, category, description, price) values (73, 'fusce consequat nulla', 'Home', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 101.8021);
insert into products (id, name, category, description, price) values (74, 'aliquet ultrices', 'Other', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis', 55.4639);
insert into products (id, name, category, description, price) values (75, 'erat curabitur', 'Other', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 141.675);
insert into products (id, name, category, description, price) values (76, 'massa id', 'Fashion', 'libero ut massa volutpat convallis morbi odio odio elementum eu', 74.5441);
insert into products (id, name, category, description, price) values (77, 'vestibulum ante ipsum', 'Home', 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 131.0856);
insert into products (id, name, category, description, price) values (78, 'lobortis est', 'Toys', 'sapien non mi integer ac neque duis bibendum morbi non quam', 52.4214);
insert into products (id, name, category, description, price) values (79, 'lectus in est', 'Fashion', 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 115.4558);
insert into products (id, name, category, description, price) values (80, 'suscipit nulla', 'Toys', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut', 108.2522);
insert into products (id, name, category, description, price) values (81, 'ut nunc vestibulum', 'Art', 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede', 2.2377);
insert into products (id, name, category, description, price) values (82, 'curae nulla', 'Electronics', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', 131.146);
insert into products (id, name, category, description, price) values (83, 'justo', 'Home', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer', 86.1167);
insert into products (id, name, category, description, price) values (84, 'sit amet consectetuer', 'Other', 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', 132.091);
insert into products (id, name, category, description, price) values (85, 'in est', 'Fashion', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique', 64.7096);
insert into products (id, name, category, description, price) values (86, 'ligula', 'Fashion', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 6.9963);
insert into products (id, name, category, description, price) values (87, 'leo maecenas', 'Other', 'ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 110.8371);
insert into products (id, name, category, description, price) values (88, 'cum sociis', 'Electronics', 'rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 82.7978);
insert into products (id, name, category, description, price) values (89, 'tortor', 'Electronics', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 9.5472);
insert into products (id, name, category, description, price) values (90, 'magnis dis parturient', 'Art', 'ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 112.7074);
insert into products (id, name, category, description, price) values (91, 'donec', 'Toys', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', 21.6141);
insert into products (id, name, category, description, price) values (92, 'nulla dapibus', 'Fashion', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 93.4509);
insert into products (id, name, category, description, price) values (93, 'porttitor pede justo', 'Art', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', 29.9428);
insert into products (id, name, category, description, price) values (94, 'quam pharetra', 'Home', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 17.9225);
insert into products (id, name, category, description, price) values (95, 'proin', 'Toys', 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', 116.4211);
insert into products (id, name, category, description, price) values (96, 'in hac', 'Art', 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 141.6745);
insert into products (id, name, category, description, price) values (97, 'ipsum praesent', 'Fashion', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', 148.3893);
insert into products (id, name, category, description, price) values (98, 'venenatis turpis', 'Art', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', 77.3018);
insert into products (id, name, category, description, price) values (99, 'odio', 'Art', 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 76.8754);
insert into products (id, name, category, description, price) values (100, 'orci', 'Art', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', 38.8892);