create table users (
	id INT,
	username VARCHAR(50),
	email VARCHAR(50),
	date_of_registration DATE,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	country VARCHAR(50),
	gender VARCHAR(50)
);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (1, 'pheathwood0', 'pheathwood0@feedburner.com', '2018-11-13', 'Paola', 'Heathwood', 'Croatia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (2, 'dcrampsy1', 'dcrampsy1@artisteer.com', '2018-11-08', 'Daveen', 'Crampsy', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (3, 'whucklesby2', 'whucklesby2@odnoklassniki.ru', '2018-10-10', 'Welsh', 'Hucklesby', 'Sweden', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (4, 'lterbeek3', 'hpickard3@discovery.com', '2019-04-12', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (5, 'mriddeough4', 'mriddeough4@reuters.com', '2019-04-19', 'Mara', 'Riddeough', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (6, 'hdunsleve5', 'ipriddis5@upenn.edu', '2019-02-28', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (7, 'tbruyett6', 'tbruyett6@etsy.com', '2018-10-06', 'Tammie', 'Bruyett', 'Yemen', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (8, 'broddie7', 'broddie7@epa.gov', '2019-05-21', 'Bette-ann', 'Roddie', 'Albania', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (9, 'ctidey8', 'ctidey8@soundcloud.com', '2019-03-19', 'Cornie', 'Tidey', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (10, 'pfrangione9', 'pfrangione9@nymag.com', '2019-05-17', 'Pembroke', 'Frangione', 'Philippines', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (11, 'mtulleya', 'mtulleya@mapy.cz', '2019-02-18', 'Mathe', 'Tulley', 'South Africa', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (12, 'mmckeab', 'mmckeab@businessinsider.com', '2018-07-07', 'Maudie', 'McKea', 'Philippines', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (13, 'mszantoc', 'mszantoc@usnews.com', '2019-02-22', 'Meridith', 'Szanto', 'Pakistan', null);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (14, 'nnaired', 'nnaired@furl.net', '2018-07-02', 'Neal', 'Naire', 'Brazil', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (15, 'sarrowsmithe', 'sarrowsmithe@imdb.com', '2018-11-19', 'Scottie', 'Arrowsmith', 'France', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (16, 'ldictyf', 'ldictyf@canalblog.com', '2018-09-10', 'Lonny', 'Dicty', 'Portugal', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (17, 'yedmandg', 'yedmandg@statcounter.com', '2018-10-29', 'Yuri', 'Edmand', 'Indonesia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (18, 'gstancerh', 'gstancerh@macromedia.com', '2019-05-10', 'Giovanni', 'Stancer', 'Jamaica', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (19, 'epinwelli', 'epinwelli@nhs.uk', '2019-04-14', 'Edita', 'Pinwell', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (20, 'sgabbattj', 'sgabbattj@opera.com', '2018-07-18', 'Sherye', 'Gabbatt', 'Brazil', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (21, 'bsurgenork', 'bsurgenork@typepad.com', '2018-12-07', 'Bebe', 'Surgenor', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (22, 'fhuttl', 'fhuttl@ning.com', '2018-07-26', 'Florella', 'Hutt', 'Sweden', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (23, 'mghionm', 'mghionm@google.nl', '2018-10-16', 'Moises', 'Ghion', 'Indonesia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (24, 'gbuckbeen', 'gbuckbeen@dailymotion.com', '2019-04-30', 'Gayel', 'Buckbee', 'Mexico', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (25, 'bmaccollo', 'bmaccollo@hp.com', '2018-10-31', 'Benny', 'MacColl', 'United Arab Emirates', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (26, 'eyeelesp', 'eyeelesp@creativecommons.org', '2018-12-28', 'Eric', 'Yeeles', 'United Kingdom', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (27, 'eprowtingq', 'eprowtingq@cisco.com', '2019-02-08', 'Elisabet', 'Prowting', 'Ukraine', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (28, 'ktrewettr', 'ktrewettr@mysql.com', '2018-11-29', 'Kellen', 'Trewett', 'Indonesia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (29, 'pbevanss', 'pbevanss@eventbrite.com', '2019-02-24', 'Patton', 'Bevans', 'France', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (30, 'scapelowt', 'scapelowt@google.fr', '2018-12-20', 'Shelby', 'Capelow', 'Russia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (31, 'kwalpoleu', 'kwalpoleu@cafepress.com', '2019-02-04', 'Kelsey', 'Walpole', 'Czech Republic', null);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (32, 'sbendellv', 'sbendellv@devhub.com', '2019-03-20', 'Sherline', 'Bendell', 'Russia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (33, 'mfeenyw', 'mfeenyw@rambler.ru', '2018-11-29', 'Myrta', 'Feeny', 'Bangladesh', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (34, 'dteazx', 'dteazx@taobao.com', '2019-02-11', 'Dunc', 'Teaz', 'Kazakhstan', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (35, 'raubruny', 'raubruny@vimeo.com', '2019-01-01', 'Renaud', 'Aubrun', 'Brazil', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (36, 'pchoupinz', 'pchoupinz@jugem.jp', '2019-04-23', 'Persis', 'Choupin', 'Pakistan', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (37, 'nebertz10', 'nebertz10@yellowpages.com', '2018-10-03', 'Noni', 'Ebertz', 'Netherlands', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (38, 'wmalatalant11', 'wmalatalant11@sphinn.com', '2018-10-23', 'Woodman', 'Malatalant', 'Costa Rica', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (39, 'mknevet12', 'mknevet12@issuu.com', '2018-12-21', 'Mara', 'Knevet', 'Argentina', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (40, 'nsproson13', 'nsproson13@house.gov', '2019-02-27', 'Noel', 'Sproson', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (41, 'fdudney14', 'zwhitington14@vk.com', '2018-12-06', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (42, 'dcavee15', 'dcavee15@dedecms.com', '2019-04-09', 'Duky', 'Cavee', 'United States', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (43, 'rlies16', 'rlies16@nasa.gov', '2019-04-13', 'Rey', 'Lies', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (44, 'renderby17', 'renderby17@nsw.gov.au', '2019-02-17', 'Rossy', 'Enderby', 'Brazil', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (45, 'dilsley18', 'dilsley18@gravatar.com', '2018-09-11', 'Di', 'Ilsley', 'Indonesia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (46, 'cdrissell19', 'cdrissell19@springer.com', '2018-06-08', 'Costanza', 'Drissell', 'China', null);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (47, 'gsmead1a', 'gsmead1a@acquirethisname.com', '2018-07-12', 'Grantley', 'Smead', 'Thailand', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (48, 'srearie1b', 'srearie1b@house.gov', '2018-08-17', 'Skipton', 'Rearie', 'Poland', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (49, 'aaleavy1c', 'aaleavy1c@google.com.hk', '2018-09-11', 'Angelo', 'Aleavy', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (50, 'tolehane1d', 'tolehane1d@seesaa.net', '2018-12-28', 'Thurston', 'O''Lehane', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (51, 'uacock1e', 'uacock1e@theatlantic.com', '2019-04-10', 'Urban', 'Acock', 'France', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (52, 'hmacallister1f', 'hmacallister1f@state.tx.us', '2018-10-06', 'Harmon', 'MacAllister', 'South Africa', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (53, 'ctheobalds1g', 'ctheobalds1g@netvibes.com', '2018-08-09', 'Crysta', 'Theobalds', 'Egypt', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (54, 'probeiro1h', 'probeiro1h@newsvine.com', '2019-02-03', 'Pia', 'Robeiro', 'Philippines', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (55, 'mgoaley1i', 'mgoaley1i@soundcloud.com', '2019-02-09', 'Maxie', 'Goaley', 'Ukraine', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (56, 'etroy1j', 'etroy1j@google.cn', '2019-01-11', 'Erinna', 'Troy', 'Vietnam', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (57, 'rmarchand1k', 'rmarchand1k@sogou.com', '2019-01-13', 'Roshelle', 'Marchand', 'Czech Republic', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (58, 'mklimuk1l', 'mklimuk1l@github.io', '2018-08-30', 'Madelle', 'Klimuk', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (59, 'ajinkinson1m', 'ajinkinson1m@dailymotion.com', '2018-12-28', 'Alva', 'Jinkinson', 'Russia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (60, 'rhaddock1n', 'rhaddock1n@jalbum.net', '2019-02-01', 'Rhona', 'Haddock', 'Philippines', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (61, 'swillshire1o', 'swillshire1o@fda.gov', '2018-07-20', 'Sawyere', 'Willshire', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (62, 'cgredden1p', 'cgredden1p@dot.gov', '2019-05-21', 'Claribel', 'Gredden', 'United States', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (63, 'bfellnee1q', 'bfellnee1q@state.gov', '2018-12-21', 'Bartolemo', 'Fellnee', 'Philippines', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (64, 'cwilloughey1r', 'cwilloughey1r@patch.com', '2019-04-20', 'Colette', 'Willoughey', 'Armenia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (65, 'ssadry1s', 'ssadry1s@miitbeian.gov.cn', '2018-09-29', 'Sunshine', 'Sadry', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (66, 'churley1t', 'churley1t@istockphoto.com', '2019-03-03', 'Corey', 'Hurley', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (67, 'kclothier1u', 'kclothier1u@mapquest.com', '2018-09-08', 'Karie', 'Clothier', 'Poland', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (68, 'kmcgillreich1v', 'kmcgillreich1v@dedecms.com', '2019-05-07', 'Kare', 'McGillreich', 'France', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (69, 'kbrownill1w', 'kbrownill1w@bbb.org', '2019-05-15', 'Kimberly', 'Brownill', 'Gambia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (70, 'csinderland1x', 'csinderland1x@ucoz.ru', '2018-09-20', 'Clayborne', 'Sinderland', 'Sweden', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (71, 'lrubinow1y', 'lrubinow1y@pbs.org', '2018-10-23', 'Lenka', 'Rubinow', 'Uganda', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (72, 'amacbey1z', 'amacbey1z@umn.edu', '2019-05-19', 'Abe', 'MacBey', 'Honduras', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (73, 'hdelhay20', 'sgiggs20@i2i.jp', '2018-10-25', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (74, 'ebohl21', 'ebohl21@reuters.com', '2018-06-19', 'Ericha', 'Bohl', 'Argentina', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (75, 'dedwin22', 'dedwin22@issuu.com', '2019-03-30', 'Daphna', 'Edwin', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (76, 'eturnbull23', 'eturnbull23@wikia.com', '2018-07-21', 'Ely', 'Turnbull', 'China', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (77, 'pgosse24', 'pgosse24@msn.com', '2018-12-05', 'Pammy', 'Gosse', 'Canada', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (78, 'craddon25', 'craddon25@jiathis.com', '2018-11-09', 'Carena', 'Raddon', 'Czech Republic', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (79, 'nhorsted26', 'nhorsted26@t.co', '2018-08-19', 'Nevin', 'Horsted', 'Spain', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (80, 'againsburgh27', 'againsburgh27@redcross.org', '2018-10-27', 'Ailyn', 'Gainsburgh', 'Thailand', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (81, 'dpeer28', 'dpeer28@mac.com', '2018-12-08', 'Dulcinea', 'Peer', 'Hungary', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (82, 'ldjurdjevic29', 'ldjurdjevic29@japanpost.jp', '2018-10-11', 'Lorelle', 'Djurdjevic', 'Cambodia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (83, 'mlampen2a', 'mlampen2a@globo.com', '2018-12-01', 'Matelda', 'Lampen', 'China', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (84, 'mphilipp2b', 'mphilipp2b@chicagotribune.com', '2019-01-12', 'Marilin', 'Philipp', 'Paraguay', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (85, 'tmclice2c', 'tmclice2c@studiopress.com', '2019-05-02', 'Tiffani', 'McLice', 'Brazil', null);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (86, 'abuckler2d', 'abuckler2d@google.com.au', '2019-03-14', 'Arlette', 'Buckler', 'Thailand', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (87, 'lwalliker2e', 'lwalliker2e@flickr.com', '2019-04-20', 'Larina', 'Walliker', 'Thailand', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (88, 'dlefloch2f', 'dlefloch2f@slate.com', '2019-03-18', 'Dallis', 'Le Floch', 'Indonesia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (89, 'mmackleden2g', 'mmackleden2g@about.com', '2018-09-25', 'Myrvyn', 'Mackleden', 'Portugal', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (90, 'fblondin2h', 'tchritchley2h@seattletimes.com', '2018-09-10', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (91, 'jkiddye2i', 'jkiddye2i@ft.com', '2018-07-29', 'Jeana', 'Kiddye', 'Russia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (92, 'jcuell2j', 'jcuell2j@bandcamp.com', '2019-03-27', 'Junie', 'Cuell', 'Costa Rica', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (93, 'pstephens2k', 'pstephens2k@goo.gl', '2018-08-14', 'Patten', 'Stephens', 'Russia', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (94, 'odoncaster2l', 'odoncaster2l@cdbaby.com', '2019-03-29', 'Orland', 'Doncaster', 'Bulgaria', 'Male');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (95, 'kcrookall2m', 'lthompstone2m@state.gov', '2018-08-08', null, null, null, 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (96, 'cduns2n', 'cduns2n@google.pl', '2018-11-22', 'Chantal', 'Duns', 'Croatia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (97, 'bodogherty2o', 'bodogherty2o@pen.io', '2018-08-07', 'Bette-ann', 'O''Dogherty', 'Russia', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (98, 'kcogdon2p', 'kcogdon2p@nbcnews.com', '2018-09-22', 'Karna', 'Cogdon', 'Poland', 'Female');
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (99, 'wtipens2q', 'mbranni2q@ovh.net', '2018-06-13', null, null, null, null);
insert into users (id, username, email, date_of_registration, first_name, last_name, country, gender) values (100, 'bnardoni2r', 'bnardoni2r@reference.com', '2018-07-15', 'Brian', 'Nardoni', 'Colombia', 'Male');